# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions currently msgtools is MIT, MTurkR is GPL-2, translateR is GPL-3
 - [ ] Reporting framework
-->

Projects will be hosted on github and include issue trackers.

The packages will be licensed under the GNU GPL-3.

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

### Week 1 to 2

- Create github repositories for the human and automated translation packages.
- Determine the end-user interfaces, that is the high-level functions that are needed in order to have a sensible workflow.
- Work on documentation for the *msgtools* package.

### Week 3 to 4

- Work on functionality for parsing, reading, and writing `PO` files.
- Create functionality for automated translation of all messages in a package via Google Translate.

### Week 5 to 6

- Extend functionality for automated translation to Microsoft Translator backend.
- More work on *msgtools* making translations easy to integrate into packages.
- Research existing translation tasks on Amazon Mechanical Turk.

### Week 7 to 8

- Extend *msgtools* to work with C-level translations.
- Create functionality to send a translation task to Amazon Mechanical Turk.

### Week 9 to 10

- Optimise Mechanical Turk template via A/B testing.
- Create functionality in *msgtools* for finding content that needs to be translated.

### Week 11 to 12

- Testing translation tools on existing packages of the authors.

### Week 13 to 14

- Providing translations for high profile packages such as *ggplot2*, *Rcpp* and *(d)plyr*.

### Week 15 to 16

- Final tidying up of packages.

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

The developers will publicise the project via their respective blogs, [http://4dpiecharts.com](4dpiecharts.com) and [thomasleeper.com](http://thomasleeper.com/blog.html), and via twitter.

The developers will present on the project at the useR! conference in 2016 if their employers agree to fund their attendance at the conference.
